### ISSUE TITLE
Update the dark ASCII cat 

### ISSUE THREAD

**Issue by davi-miquelim** [catppuccin/wallpapers#33]
Update the dark ASCII cat  to be compatible with ultrawide monitors

**Comment by Pocco81** [comment]
Mind linking the wallpaper(s) on matter?

**Comment by davi-miquelim** [comment]
Hey @Pocco81  here is the wallpaper https://github.com/catppuccin/wallpapers/blob/main/minimalistic/dark-cat.png

**Comment by isabelincorp** [comment]
I will probably figure out a way to redo these wallpapers but most likely, since the wallpaper is so simple, you can just make an image in gimp at the resolution of your monitor, plop in the wallpaper then fill in the background with the color of the background.

I'm not sure if we are going to support ultrawide wallpapers or not because it adds more maintenance.
