### ISSUE TITLE
Can I use some of your wallaper in my pack?

### ISSUE THREAD

**Issue by Akergez** [catppuccin/wallpapers#52]
I forked pack with dynamic wallpapers for gnome and i would like to add some of your wallpaper (from os folder) in it. https://github.com/Akergez/Linux_Dynamic_Wallpapers_Locally

**Comment by isabelincorp** [comment]
Sure, just make sure to credit accordingly (to the repository)! I plan on taking off some wallpapers due to them not applying to the “new” 0.2.0 flavours so be aware some wallpapers you use from here could be gone at a later time; those that are staying are still being added to [the 0.2.0 branch](https://github.com/catppuccin/wallpapers/tree/0.2.0). 

Also, nice repo!
