### ISSUE TITLE
include svgs 

### ISSUE THREAD

**Issue by Maciejfiedler** [catppuccin/wallpapers#6]
these wallpapers are all great but these are all png, so they are cannot be edited. it would be cool if could include an svg directory to every directory of wallpapers so people can create a wallppaer with their own pastel colorscheme

**Comment by Pocco81** [comment]
So like... An SVG per wallpaper?

**Comment by Maciejfiedler** [comment]
yes

**Comment by Pocco81** [comment]
Sorry, but I don't think that'd be possible. Most wallpapers are simply recolorized. Also because they tend to use different art styles, which means that they can't be exported to SVGs.

However, there are org-wide assets (most of which are SVGs) that you can find under the main repo: https://github.com/catppuccin/catppuccin/tree/main/assets
